import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Navbar } from "@/components/Navbar";
import { Inter } from 'next/font/google'
import Providers from "@/components/Providers";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "BrainBolt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={
          cn(
            inter.className,
            'antialiased min-h-screen pt-16')
        }
      >
        <Providers>
          <Navbar />
          {children}
          <Toaster />
        </Providers> 
      </body>
    </html>
  );
}
